# Generated by Django 5.0.4 on 2024-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0002_alter_watchlist_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie_poster',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='img/'),
        ),
    ]
