# Generated by Django 5.0.4 on 2024-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0003_watchlist_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie_poster',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='img/'),
        ),
    ]
